define({
  "defaultAreaUnit": "Unità di superficie predefinita",
  "defaultLengthUnit": "Unità di lunghezza predefinita",
  "metric": "Metrico",
  "imperial": "Imperiale",
  "squareKilometers": "Chilometri quadrati",
  "squareMeters": "Metri quadrati",
  "squareMiles": "Miglia quadrate",
  "squareInches": "Pollici quadrati",
  "squareFeet": "Piedi quadrati",
  "squareYards": "Iarde quadrate",
  "squareUSFeet": "Piede quadrato (USA)",
  "acres": "Acri",
  "ares": "Are",
  "hectares": "Ettari",
  "inches": "Pollici",
  "feet": "Piedi",
  "yards": "Iarde",
  "miles": "Miglia",
  "nauticalMiles": "Miglia nautiche",
  "feetUS": "Piede (USA)",
  "meters": "Metri",
  "kilometers": "Chilometri",
  "showArea": "Area",
  "showDistance": "Distanza",
  "showLocation": "Posizione",
  "showtools": "Mostra strumenti di misurazione:",
  "allHidedTips": "Selezionare almeno uno strumento."
});