define({
  "defaultAreaUnit": "Unité de surface par défaut",
  "defaultLengthUnit": "Unité de longueur par défaut",
  "metric": "Métriques",
  "imperial": "Impériales",
  "squareKilometers": "Kilomètres carrés",
  "squareMeters": "Mètres carrés",
  "squareMiles": "Miles carrés",
  "squareInches": "Pouces carrés",
  "squareFeet": "Pieds carrés",
  "squareYards": "Yards carrés",
  "squareUSFeet": "Pieds carrés (US)",
  "acres": "Ares",
  "ares": "Ares",
  "hectares": "Hectares",
  "inches": "Pouces",
  "feet": "Pieds",
  "yards": "Yards",
  "miles": "Milles",
  "nauticalMiles": "Milles nautiques",
  "feetUS": "Pieds (US)",
  "meters": "Mètres",
  "kilometers": "Kilomètres",
  "showArea": "Surface",
  "showDistance": "Distance",
  "showLocation": "Emplacement",
  "showtools": "Afficher les outils de mesure :",
  "allHidedTips": "Au moins un outil doit être sélectionné."
});