define({
  "defaultAreaUnit": "기본 면적 단위",
  "defaultLengthUnit": "기본 길이 단위",
  "metric": "미터법",
  "imperial": "영국식",
  "squareKilometers": "제곱킬로미터",
  "squareMeters": "제곱미터",
  "squareMiles": "제곱마일",
  "squareInches": "제곱인치",
  "squareFeet": "제곱피트",
  "squareYards": "제곱야드",
  "squareUSFeet": "제곱피트(미국)",
  "acres": "에이커",
  "ares": "아르",
  "hectares": "헥타르",
  "inches": "인치",
  "feet": "피트",
  "yards": "야드",
  "miles": "마일",
  "nauticalMiles": "해리",
  "feetUS": "피트(미국)",
  "meters": "m",
  "kilometers": "킬로미터",
  "showArea": "영역",
  "showDistance": "거리(Distance)",
  "showLocation": "위치",
  "showtools": "측정 도구 표시:",
  "allHidedTips": "최소 하나의 도구를 선택해야 합니다."
});