define({
  "defaultAreaUnit": "Varsayılan alan birimi",
  "defaultLengthUnit": "Varsayılan uzunluk birimi",
  "metric": "Metrik",
  "imperial": "İngiliz",
  "squareKilometers": "Kilometre Kare",
  "squareMeters": "Metre Kare",
  "squareMiles": "Mil Kare",
  "squareInches": "İnç Kare",
  "squareFeet": "Fit Kare",
  "squareYards": "Yarda Kare",
  "squareUSFeet": "Fit Kare (ABD)",
  "acres": "Akre",
  "ares": "Ar",
  "hectares": "Hektar",
  "inches": "İnç",
  "feet": "Fit",
  "yards": "Yarda",
  "miles": "Mil",
  "nauticalMiles": "Deniz Mili",
  "feetUS": "Fit (ABD)",
  "meters": "Metre",
  "kilometers": "Kilometre",
  "showArea": "Alan",
  "showDistance": "Mesafe",
  "showLocation": "Konum",
  "showtools": "Ölçüm araçlarını göster:",
  "allHidedTips": "En az bir araç seçilmelidir."
});