define({
  "defaultAreaUnit": "Unidade de área padrão",
  "defaultLengthUnit": "Unidade de comprimento padrão",
  "metric": "Métrico",
  "imperial": "Imperial",
  "squareKilometers": "Quilômetros Quadrados",
  "squareMeters": "Metros Quadrados",
  "squareMiles": "Milhas Quadradas",
  "squareInches": "Polegadas Quadradas",
  "squareFeet": "Pés Quadrados",
  "squareYards": "Jardas Quadradas",
  "squareUSFeet": "Pés Quadrados (US)",
  "acres": "Acres",
  "ares": "Ares",
  "hectares": "Hectares",
  "inches": "Polegadas",
  "feet": "Pés",
  "yards": "Jardas",
  "miles": "Milhas",
  "nauticalMiles": "Milhas Náuticas",
  "feetUS": "Pés (US)",
  "meters": "Metros",
  "kilometers": "Quilômetros",
  "showArea": "Área",
  "showDistance": "Distância",
  "showLocation": "Localização",
  "showtools": "Mostrar ferramentas de medição:",
  "allHidedTips": "Pelo menos uma ferramenta deve ser selecionada."
});