define({
  "defaultAreaUnit": "Standard arealenhet",
  "defaultLengthUnit": "Standard lengdeenhet",
  "metric": "Metrisk",
  "imperial": "Britiske målenheter",
  "squareKilometers": "km²",
  "squareMeters": "m²",
  "squareMiles": "miles²",
  "squareInches": "tommer²",
  "squareFeet": "fot²",
  "squareYards": "yard²",
  "squareUSFeet": "kvadratfot (USA)",
  "acres": "Dekar",
  "ares": "ar",
  "hectares": "Hektar",
  "inches": "Tommer",
  "feet": "Fot",
  "yards": "Yard",
  "miles": "Miles",
  "nauticalMiles": "Nautiske mil",
  "feetUS": "fot (USA)",
  "meters": "Meter",
  "kilometers": "Kilometer",
  "showArea": "Areal",
  "showDistance": "Avstand",
  "showLocation": "Plassering",
  "showtools": "Vis måleverktøy:",
  "allHidedTips": "Du må velge minst ett verktøy."
});