define({
  "defaultAreaUnit": "Domyślna jednostka powierzchni",
  "defaultLengthUnit": "Domyślna jednostka długości",
  "metric": "Metryczne",
  "imperial": "Angielskie",
  "squareKilometers": "Kilometry kw.",
  "squareMeters": "Metry kw.",
  "squareMiles": "Mile kw.",
  "squareInches": "Cale kw.",
  "squareFeet": "Stopy kw.",
  "squareYards": "Jardy kw.",
  "squareUSFeet": "Stopy kw. (US)",
  "acres": "Akry",
  "ares": "Ary",
  "hectares": "Hektary",
  "inches": "Cale",
  "feet": "Stopy",
  "yards": "Jardy",
  "miles": "Mile",
  "nauticalMiles": "Mile morskie",
  "feetUS": "Stopy (US)",
  "meters": "Metry",
  "kilometers": "Kilometry",
  "showArea": "Pole powierzchni",
  "showDistance": "Odległość",
  "showLocation": "Lokalizacja",
  "showtools": "Pokaż narzędzia pomiarowe:",
  "allHidedTips": "Należy wybrać co najmniej jedno narzędzie."
});