define({
  "defaultAreaUnit": "Numatytieji ploto vienetai",
  "defaultLengthUnit": "Numatytasis ilgio vienetas",
  "metric": "Metriniai",
  "imperial": "Imperiniai",
  "squareKilometers": "Kv. kilometrai",
  "squareMeters": "Kv. metrai",
  "squareMiles": "Kv. mylios",
  "squareInches": "Kv. coliai",
  "squareFeet": "Kv. pėdos",
  "squareYards": "Kv. jardai",
  "squareUSFeet": "Kv. pėdos (JAV)",
  "acres": "Akrai",
  "ares": "Arai",
  "hectares": "Hektarai",
  "inches": "Coliai",
  "feet": "Pėdos",
  "yards": "Jardai",
  "miles": "Mylios",
  "nauticalMiles": "Jūrmylės",
  "feetUS": "Pėdos (JAV)",
  "meters": "Metrai",
  "kilometers": "Kilometrai",
  "showArea": "Plotas",
  "showDistance": "Atstumas",
  "showLocation": "Padėtis",
  "showtools": "Rodyti matavimo įrankius:",
  "allHidedTips": "Būtina pasirinkti bent vieną įrankį."
});