define({
  "defaultAreaUnit": "Standardenhet för yta",
  "defaultLengthUnit": "Standardenhet för längd",
  "metric": "Metriska",
  "imperial": "Imperial",
  "squareKilometers": "Kvadratkilometer",
  "squareMeters": "Kvadratmeter",
  "squareMiles": "Engelska kvadratmil",
  "squareInches": "Kvadrattum",
  "squareFeet": "Kvadratfot",
  "squareYards": "Kvadratyard",
  "squareUSFeet": "Kvadratfot (USA)",
  "acres": "Tunnland",
  "ares": "Ar",
  "hectares": "Hektar",
  "inches": "Tum",
  "feet": "Fot",
  "yards": "Yard",
  "miles": "Mile",
  "nauticalMiles": "Nautiska mil",
  "feetUS": "Fot (USA)",
  "meters": "Meter",
  "kilometers": "Kilometer",
  "showArea": "Område",
  "showDistance": "Avstånd",
  "showLocation": "Plats",
  "showtools": "Visa mätverktyg:",
  "allHidedTips": "Minst ett verktyg måste väljas."
});