define({
  "defaultAreaUnit": "Unitate de suprafață implicită",
  "defaultLengthUnit": "Unitate de lungime implicită",
  "metric": "Metric",
  "imperial": "Englez",
  "squareKilometers": "Kilometri pătrați",
  "squareMeters": "Metri pătrați",
  "squareMiles": "Mile pătrate",
  "squareInches": "Inci pătrați",
  "squareFeet": "Picioare pătrate",
  "squareYards": "Yarzi pătrați",
  "squareUSFeet": "Picioare pătrate (SUA)",
  "acres": "Acri",
  "ares": "Ari",
  "hectares": "Hectare",
  "inches": "Inci",
  "feet": "Ft",
  "yards": "Yarzi",
  "miles": "Mile",
  "nauticalMiles": "Mile marine",
  "feetUS": "Picioare (SUA)",
  "meters": "Metri",
  "kilometers": "Kilometri",
  "showArea": "Suprafaţă",
  "showDistance": "Distanţă",
  "showLocation": "Locaţie",
  "showtools": "Afişare instrumente de măsură:",
  "allHidedTips": "Trebuie selectat cel puţin un instrument."
});