define({
  "defaultAreaUnit": "Đơn vị diện tích mặc định",
  "defaultLengthUnit": "Đơn vị độ dài mặc định",
  "metric": "Hệ mét",
  "imperial": "Hệ đo lường Anh",
  "squareKilometers": "Kilômét vuông",
  "squareMeters": "Mét vuông",
  "squareMiles": "Dặm vuông",
  "squareInches": "Inch Vuông",
  "squareFeet": "Feet vuông",
  "squareYards": "Thước vuông",
  "squareUSFeet": "Feet vuông (Hoa Kỳ)",
  "acres": "Acre",
  "ares": "Are",
  "hectares": "Hecta",
  "inches": "Inch",
  "feet": "Bộ",
  "yards": "Thước",
  "miles": "Dặm",
  "nauticalMiles": "Hải lý",
  "feetUS": "Feet (Hoa Kỳ)",
  "meters": "Mét",
  "kilometers": "Kilômét",
  "showArea": "Khu vực",
  "showDistance": "Khoảng cách",
  "showLocation": "Vị trí",
  "showtools": "Hiện công cụ đo lường:",
  "allHidedTips": "Phải chọn ít nhất một công cụ."
});