define({
  "defaultAreaUnit": "Alapértelmezett terület-mértékegység",
  "defaultLengthUnit": "Alapértelmezett hosszmértékegység",
  "metric": "Metrikus",
  "imperial": "Angolszász",
  "squareKilometers": "négyzetkilométer",
  "squareMeters": "négyzetméter",
  "squareMiles": "négyzetmérföld",
  "squareInches": "négyzethüvelyk",
  "squareFeet": "négyzetláb",
  "squareYards": "négyzetyard",
  "squareUSFeet": "négyzetláb (US)",
  "acres": "Acre",
  "ares": "Ár",
  "hectares": "Hektár",
  "inches": "Hüvelyk",
  "feet": "Láb",
  "yards": "Yard",
  "miles": "Mérföld",
  "nauticalMiles": "Tengeri mérföld",
  "feetUS": "Láb (US)",
  "meters": "Méter",
  "kilometers": "Kilométer",
  "showArea": "Terület",
  "showDistance": "Távolság",
  "showLocation": "Hely",
  "showtools": "Mérési eszközök megjelenítése:",
  "allHidedTips": "Legalább egy eszközt ki kell választani."
});