define({
  "defaultAreaUnit": "Unidade de área predefinida",
  "defaultLengthUnit": "Unidade de comprimento predefinida",
  "metric": "Métrico",
  "imperial": "Imperial",
  "squareKilometers": "Quilómetros Quadrados",
  "squareMeters": "Metros Quadrados",
  "squareMiles": "Milhas Quadradas",
  "squareInches": "Polegadas Quadradas",
  "squareFeet": "Pés Quadrados",
  "squareYards": "Jardas Quadradas",
  "squareUSFeet": "Pés Quadrados (EUA)",
  "acres": "Acres",
  "ares": "Ares",
  "hectares": "Hectares",
  "inches": "Polegadas",
  "feet": "Pés",
  "yards": "Jardas",
  "miles": "Milhas",
  "nauticalMiles": "Milhas Náuticas",
  "feetUS": "Pés (EUA)",
  "meters": "Metros",
  "kilometers": "Quilómetros",
  "showArea": "Área",
  "showDistance": "Distância",
  "showLocation": "Localização",
  "showtools": "Exibir ferramentas de medição:",
  "allHidedTips": "Tem de ser selecionada pelo menos uma ferramenta."
});