define({
  "defaultAreaUnit": "Standaard oppervlakte-eenheid",
  "defaultLengthUnit": "Standaard lengte-eenheid",
  "metric": "Metrisch",
  "imperial": "Imperiaal",
  "squareKilometers": "Vierkante kilometers",
  "squareMeters": "Vierkante meters",
  "squareMiles": "Vierkante mile",
  "squareInches": "Vierkante inch",
  "squareFeet": "Vierkante voet",
  "squareYards": "Vierkante yard",
  "squareUSFeet": "Viekante voet (US)",
  "acres": "Acres",
  "ares": "Are",
  "hectares": "Hectare",
  "inches": "Inch",
  "feet": "Voet",
  "yards": "Yard",
  "miles": "Mijl",
  "nauticalMiles": "Zeemijl",
  "feetUS": "Voet (US)",
  "meters": "Meter",
  "kilometers": "Kilometer",
  "showArea": "Gebied",
  "showDistance": "Afstand",
  "showLocation": "Locatie",
  "showtools": "Toon meetgereedschappen:",
  "allHidedTips": "Er moet minimaal één gereedschap worden geselecteerd."
});