define({
  "defaultAreaUnit": "Προεπιλεγμένη μονάδα εμβαδού",
  "defaultLengthUnit": "Προεπιλεγμένη μονάδα μήκους",
  "metric": "Μετρικό σύστημα",
  "imperial": "Βρετανικό σύστημα",
  "squareKilometers": "Τετρ. χιλιόμετρα",
  "squareMeters": "Τετρ. μέτρα",
  "squareMiles": "Τετρ. μίλια",
  "squareInches": "Τετρ. ίντσες",
  "squareFeet": "Τετρ. πόδια",
  "squareYards": "Τετρ. γιάρδες",
  "squareUSFeet": "Τετρ. πόδια (US)",
  "acres": "Έικρ",
  "ares": "Άρια",
  "hectares": "Εκτάρια",
  "inches": "Ίντσες",
  "feet": "Πόδια",
  "yards": "Γιάρδες",
  "miles": "Μίλια",
  "nauticalMiles": "Ναυτικά μίλια",
  "feetUS": "Πόδια (US)",
  "meters": "Μέτρα",
  "kilometers": "Χιλιόμετρα",
  "showArea": "Εμβαδόν",
  "showDistance": "Απόσταση",
  "showLocation": "Τοποθεσία",
  "showtools": "Εμφάνιση εργαλείων μέτρησης:",
  "allHidedTips": "Πρέπει να επιλεγεί τουλάχιστον ένα εργαλείο."
});