define({
  "defaultAreaUnit": "หน่วยพื้นที่ตามค่าเริ่มต้น",
  "defaultLengthUnit": "หน่วยความยาวตามค่าเริ่มต้น",
  "metric": "ระบบเมตริก",
  "imperial": "ระบบการวัด",
  "squareKilometers": "ตร. กิโลเมตร",
  "squareMeters": "ตร. เมตร",
  "squareMiles": "ตร. ไมล์",
  "squareInches": "ตร. นิ้ว",
  "squareFeet": "ตร. ฟุต",
  "squareYards": "ตร. หลา",
  "squareUSFeet": "ตารางฟุต (สหรัฐ)",
  "acres": "เอเคอร์",
  "ares": "เอเคอร์",
  "hectares": "เฮกตาร์",
  "inches": "นิ้ว",
  "feet": "ฟุต",
  "yards": "หลา",
  "miles": "ไมล์",
  "nauticalMiles": "ไมล์ทะเล",
  "feetUS": "ฟุต (สหรัฐ)",
  "meters": "เมตร",
  "kilometers": "กิโลเมตร",
  "showArea": "พื้นที่",
  "showDistance": "ระยะทาง",
  "showLocation": "ตำแหน่ง",
  "showtools": "แสดงเครื่องมือวัด:",
  "allHidedTips": "ต้องมีอย่างน้อยหนึ่งเครื่องมือที่ถูกเลือก"
});