define({
  "defaultAreaUnit": "Standardflächeneinheit",
  "defaultLengthUnit": "Standardlängeneinheit",
  "metric": "Metrisch",
  "imperial": "Britisch",
  "squareKilometers": "Quadratkilometer",
  "squareMeters": "Quadratmeter",
  "squareMiles": "Quadratmeilen",
  "squareInches": "Quadratinch",
  "squareFeet": "Quadratfuß",
  "squareYards": "Quadratyards",
  "squareUSFeet": "Quadratfuß (US)",
  "acres": "Acres",
  "ares": "Ar",
  "hectares": "Hektar",
  "inches": "Zoll",
  "feet": "Fuß",
  "yards": "Yards",
  "miles": "Meilen",
  "nauticalMiles": "Seemeilen",
  "feetUS": "Fuß (US)",
  "meters": "Meter",
  "kilometers": "Kilometer",
  "showArea": "Fläche",
  "showDistance": "Entfernung",
  "showLocation": "Position",
  "showtools": "Messwerkzeuge anzeigen:",
  "allHidedTips": "Es sollte mindestens ein Werkzeug ausgewählt werden."
});