define({
  "defaultAreaUnit": "وحدة المنطقة الافتراضية",
  "defaultLengthUnit": "وحدة الطول الافتراضية",
  "metric": "متري",
  "imperial": "الامبراطورية",
  "squareKilometers": "كيلومترات مكعبة",
  "squareMeters": "أمتار مكعبة",
  "squareMiles": "أميال مكعبة",
  "squareInches": "بوصة مكعب",
  "squareFeet": "قدم مكعب",
  "squareYards": "ياردات مكعبة",
  "squareUSFeet": "قدم مربع (الولايات المتحدة)",
  "acres": "فدان",
  "ares": "آرس",
  "hectares": "هكتار",
  "inches": "بوصة",
  "feet": "قدم",
  "yards": "ياردة",
  "miles": "أميال",
  "nauticalMiles": "أميال محايدة",
  "feetUS": "قدم (الولايات المتحدة)",
  "meters": "أمتار",
  "kilometers": "كيلومتر",
  "showArea": "المنطقة",
  "showDistance": "المسافة",
  "showLocation": "الموقع",
  "showtools": "عرض أدوات القياس:",
  "allHidedTips": "يجب تحديد أداة واحدة على الأقل."
});