define({
  "defaultAreaUnit": "Unit area default",
  "defaultLengthUnit": "Unit panjang default",
  "metric": "Metrik",
  "imperial": "Imperial",
  "squareKilometers": "Kilometer Persegi",
  "squareMeters": "Meter Persegi",
  "squareMiles": "Mil Persegi",
  "squareInches": "Inci Persegi",
  "squareFeet": "Kaki Persegi",
  "squareYards": "Yard Persegi",
  "squareUSFeet": "Kaki Persegi (AS)",
  "acres": "Acre",
  "ares": "Are",
  "hectares": "Hektare",
  "inches": "Inci",
  "feet": "Kaki",
  "yards": "Yard",
  "miles": "Mil",
  "nauticalMiles": "Mil Laut",
  "feetUS": "Kaki (AS)",
  "meters": "Meter",
  "kilometers": "Kilometer",
  "showArea": "Area",
  "showDistance": "Jarak",
  "showLocation": "Lokasi",
  "showtools": "Tampilkan alat pengukuran:",
  "allHidedTips": "Paling sedikit satu alat harus dipilih."
});