define({
  "defaultAreaUnit": "क्षेत्रफल की डिफ़ॉल्ट इकाई",
  "defaultLengthUnit": "लंबाई की डिफ़ॉल्ट इकाई",
  "metric": "मीट्रिक",
  "imperial": "इम्पीरियल",
  "squareKilometers": "वर्ग किलोमीटर",
  "squareMeters": "वर्ग मीटर",
  "squareMiles": "वर्ग मील",
  "squareInches": "वर्ग इंच",
  "squareFeet": "वर्ग फीट",
  "squareYards": "वर्ग गज़",
  "squareUSFeet": "वर्ग फीट (US)",
  "acres": "एकड़",
  "ares": "एकड़",
  "hectares": "हेक्टेयर",
  "inches": "इंच",
  "feet": "फुट",
  "yards": "गज",
  "miles": "मील",
  "nauticalMiles": "समुद्री मील",
  "feetUS": "फीट (US)",
  "meters": "मीटर",
  "kilometers": "किलोमीटर",
  "showArea": "क्षेत्र",
  "showDistance": "दूरी",
  "showLocation": "स्थान",
  "showtools": "माप टूल दिखाएं:",
  "allHidedTips": "कम से कम एक टूल का चयन किया जाना चाहिए।"
});