define({
  "defaultAreaUnit": "Zadana jedinica površine",
  "defaultLengthUnit": "Zadana jedinica duljine",
  "metric": "Metrički",
  "imperial": "Imperijalne",
  "squareKilometers": "Kvadratni kilometri",
  "squareMeters": "Kvadratni metri",
  "squareMiles": "Kvadratne milje",
  "squareInches": "Kvadratni inči",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratni jardi",
  "squareUSFeet": "Kvadratne stope (SAD)",
  "acres": "Rali",
  "ares": "Ari",
  "hectares": "Hektari",
  "inches": "Inči",
  "feet": "Stope",
  "yards": "Jardi",
  "miles": "Milje",
  "nauticalMiles": "Nautičke milje",
  "feetUS": "Stope (SAD)",
  "meters": "Metri",
  "kilometers": "Kilometri",
  "showArea": "Poligon",
  "showDistance": "Udaljenost",
  "showLocation": "Lokacija",
  "showtools": "Prikaži alate za mjerenje:",
  "allHidedTips": "Treba odabrati barem jedan alat."
});