define({
  "defaultAreaUnit": "Pindala vaikeühik",
  "defaultLengthUnit": "Pikkuse vaikeühik",
  "metric": "Meetriline",
  "imperial": "Briti",
  "squareKilometers": "Ruutkilomeetrites",
  "squareMeters": "Ruutmeetrites",
  "squareMiles": "Ruutmiilides",
  "squareInches": "Ruuttollides",
  "squareFeet": "Ruutjalgades",
  "squareYards": "Ruutjardides",
  "squareUSFeet": "Ruutjalga (USA)",
  "acres": "aakrit",
  "ares": "Aari",
  "hectares": "hektarit",
  "inches": "Tolli",
  "feet": "Jalga",
  "yards": "Jardi",
  "miles": "miili",
  "nauticalMiles": "Meremiili",
  "feetUS": "Jalga (USA)",
  "meters": "meetrit",
  "kilometers": "kilomeetrit",
  "showArea": "Kihtdiagramm",
  "showDistance": "Vahemaa",
  "showLocation": "Asukoht",
  "showtools": "Kuva mõõtmise tööriistad:",
  "allHidedTips": "Valida tuleb vähemalt üks tööriist."
});