define({
  "defaultAreaUnit": "Výchozí jednotka plochy",
  "defaultLengthUnit": "Výchozí jednotka délky",
  "metric": "Metrické",
  "imperial": "Imperiální",
  "squareKilometers": "Čtver. kilometry",
  "squareMeters": "Čtv. metry",
  "squareMiles": "Čtver. míle",
  "squareInches": "Čtver. palce",
  "squareFeet": "Čtv. stopy",
  "squareYards": "Čtv. yardy",
  "squareUSFeet": "Čtv. stopy (US)",
  "acres": "akry",
  "ares": "ary",
  "hectares": "hektary",
  "inches": "palce",
  "feet": "stopy",
  "yards": "yardy",
  "miles": "míle",
  "nauticalMiles": "námořní míle",
  "feetUS": "Stopy (US)",
  "meters": "metry",
  "kilometers": "kilometry",
  "showArea": "Plošný",
  "showDistance": "Vzdálenost",
  "showLocation": "Poloha",
  "showtools": "Zobrazit nástroje měření:",
  "allHidedTips": "Musí být vybrán alespoň jeden nástroj."
});