define({
  "defaultAreaUnit": "デフォルトの面積単位",
  "defaultLengthUnit": "デフォルトの長さ単位",
  "metric": "メートル法",
  "imperial": "ヤード・ポンド法",
  "squareKilometers": "平方キロメートル",
  "squareMeters": "平方メートル",
  "squareMiles": "平方マイル",
  "squareInches": "平方インチ",
  "squareFeet": "平方フィート",
  "squareYards": "平方ヤード",
  "squareUSFeet": "平方フィート (米国)",
  "acres": "エーカー",
  "ares": "アール",
  "hectares": "ヘクタール",
  "inches": "インチ",
  "feet": "フィート",
  "yards": "ヤード",
  "miles": "マイル",
  "nauticalMiles": "海里",
  "feetUS": "フィート (米国)",
  "meters": "メートル",
  "kilometers": "キロメートル",
  "showArea": "面積",
  "showDistance": "距離",
  "showLocation": "位置情報",
  "showtools": "計測ツールを表示:",
  "allHidedTips": "少なくとも 1 つのツールが選択されている必要があります。"
});