define({
  "defaultAreaUnit": "Privzeta enota območja",
  "defaultLengthUnit": "Privzeta enota dolžine",
  "metric": "Metrično",
  "imperial": "Anglosaško",
  "squareKilometers": "Kvadratni kilometri",
  "squareMeters": "Kvadratni metri",
  "squareMiles": "Kvadratne milje",
  "squareInches": "Kvadratni palci",
  "squareFeet": "Kvadratni čevlji",
  "squareYards": "Kvadratni jardi",
  "squareUSFeet": "Kvadratni čevlji (ZDA)",
  "acres": "Akri",
  "ares": "Ari",
  "hectares": "Hektari",
  "inches": "Palci",
  "feet": "Čevlji",
  "yards": "Jardi",
  "miles": "Milje",
  "nauticalMiles": "Navtične milje",
  "feetUS": "Čevlji (ZDA)",
  "meters": "Metri",
  "kilometers": "Kilometri",
  "showArea": "Ploščina",
  "showDistance": "Razdalja",
  "showLocation": "Lokacija",
  "showtools": "Pokaži orodja za merjenje:",
  "allHidedTips": "Izbrano mora biti vsaj eno orodje."
});