define({
  "defaultAreaUnit": "Standardenhed for område",
  "defaultLengthUnit": "Standardenhed for længde",
  "metric": "Metrisk",
  "imperial": "Britiske",
  "squareKilometers": "Kvadratkilometer",
  "squareMeters": "Kvadratmeter",
  "squareMiles": "Kvadrat-miles",
  "squareInches": "Kvadrattommer",
  "squareFeet": "Kvadratfod",
  "squareYards": "Kvadrat-yards",
  "squareUSFeet": "Kv.fod (USA)",
  "acres": "Acres",
  "ares": "Acres",
  "hectares": "Hektarer",
  "inches": "Tommer",
  "feet": "Fod",
  "yards": "Yards",
  "miles": "Miles",
  "nauticalMiles": "Sømil",
  "feetUS": "Fod (USA)",
  "meters": "Meter",
  "kilometers": "Kilometer",
  "showArea": "Område",
  "showDistance": "Afstand",
  "showLocation": "Position",
  "showtools": "Vis måleværktøjer:",
  "allHidedTips": "Mindst ét værktøj skal være valgt."
});