define({
  "defaultAreaUnit": "預設面積單位",
  "defaultLengthUnit": "預設長度單位",
  "metric": "公制",
  "imperial": "英制",
  "squareKilometers": "平方公里",
  "squareMeters": "平方公尺",
  "squareMiles": "平方英里",
  "squareInches": "平方英吋",
  "squareFeet": "平方英呎",
  "squareYards": "平方碼",
  "squareUSFeet": "平方英呎 (美制)",
  "acres": "英畝",
  "ares": "公畝",
  "hectares": "公頃",
  "inches": "英吋",
  "feet": "英呎",
  "yards": "碼",
  "miles": "英里",
  "nauticalMiles": "海浬",
  "feetUS": "英呎 (美制)",
  "meters": "公尺",
  "kilometers": "公里",
  "showArea": "面積",
  "showDistance": "距離",
  "showLocation": "位置",
  "showtools": "顯示測量工具:",
  "allHidedTips": "必須至少選擇一個工具。"
});