define({
  "defaultAreaUnit": "Oletuspinta-alayksikkö",
  "defaultLengthUnit": "Oletuspituusyksikkö",
  "metric": "Metrijärjestelmä",
  "imperial": "Mailijärjestelmä",
  "squareKilometers": "Neliökilometriä",
  "squareMeters": "Neliömetriä",
  "squareMiles": "Neliömailia",
  "squareInches": "Neliötuumaa",
  "squareFeet": "Neliöjalkaa",
  "squareYards": "Neliöjaardia",
  "squareUSFeet": "Neliöjalkaa (Yhdysvallat)",
  "acres": "Eekkeriä",
  "ares": "Aaria",
  "hectares": "Hehtaaria",
  "inches": "Tuumaa",
  "feet": "Jalkaa",
  "yards": "Jaardia",
  "miles": "Mailia",
  "nauticalMiles": "Meripeninkulmaa",
  "feetUS": "Jalkaa (Yhdysvallat)",
  "meters": "Metriä",
  "kilometers": "Kilometriä",
  "showArea": "Alue",
  "showDistance": "Etäisyys",
  "showLocation": "Sijainti",
  "showtools": "Näytä mittaustyökalut:",
  "allHidedTips": "Vähintään yksi työkalu on valittava."
});