define({
  "defaultAreaUnit": "Unidad de área predeterminada",
  "defaultLengthUnit": "Unidad de longitud predeterminada",
  "metric": "Sistema métrico",
  "imperial": "Sistema imperial",
  "squareKilometers": "Kilómetros cuadrados",
  "squareMeters": "Metros cuadrados",
  "squareMiles": "Millas cuadradas",
  "squareInches": "Pulgadas cuadradas",
  "squareFeet": "Pies cuadrados",
  "squareYards": "Yardas cuadradas",
  "squareUSFeet": "Pies cuadrados (EE. UU.)",
  "acres": "Acres",
  "ares": "Áreas",
  "hectares": "Hectáreas",
  "inches": "Pulgadas",
  "feet": "Pies",
  "yards": "Yardas",
  "miles": "Millas",
  "nauticalMiles": "Millas náuticas",
  "feetUS": "Pies (EE. UU.)",
  "meters": "Metros",
  "kilometers": "Kilómetros",
  "showArea": "Área",
  "showDistance": "Distancia",
  "showLocation": "Ubicación",
  "showtools": "Mostrar herramientas de medición:",
  "allHidedTips": "Se debe seleccionar al menos una herramienta."
});