define({
  root: ({
    "defaultAreaUnit": "Default area unit",
    "defaultLengthUnit": "Default length unit",
    "metric": "Metric",
    "imperial": "Imperial",
    "squareKilometers": "Sq Kilometers",
    "squareMeters": "Sq Meters",
    "squareMiles": "Sq Miles",
    "squareInches": "Sq Inches",
    "squareFeet": "Sq Feet",
    "squareYards": "Sq Yards",
    "squareUSFeet": "Sq Feet (US)",
    "acres": "Acres",
    "ares": "Ares",
    "hectares": "Hectares",
    "inches": "Inches",
    "feet": "Feet",
    "yards": "Yards",
    "miles": "Miles",
    "nauticalMiles": "Nautical Miles",
    "feetUS": "Feet (US)",
    "meters": "Meters",
    "kilometers": "Kilometers",
    "showArea": "Area",
    "showDistance": "Distance",
    "showLocation": "Location",
    "showtools": "Show measurement tools:",
    "allHidedTips": "At least one tool should be selected."
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});