define({
  "defaultAreaUnit": "Podrazumevana jedinica površine",
  "defaultLengthUnit": "Podrazumevana jedinica dužine",
  "metric": "Metrika",
  "imperial": "Imperijalne",
  "squareKilometers": "Kvadratni kilometri",
  "squareMeters": "Kvadratni metri",
  "squareMiles": "Kvadratne milje",
  "squareInches": "Kvadratni inči",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratni jardi",
  "squareUSFeet": "Kvadratne stope (SAD)",
  "acres": "Ari",
  "ares": "Ari",
  "hectares": "Hektari",
  "inches": "Inči",
  "feet": "Stope",
  "yards": "Jardi",
  "miles": "Milje",
  "nauticalMiles": "Nautičke milje",
  "feetUS": "Stope (SAD)",
  "meters": "Metri",
  "kilometers": "Kilometri",
  "showArea": "Površina",
  "showDistance": "Rastojanje",
  "showLocation": "Lokacija",
  "showtools": "Prikaži alate za merenje:",
  "allHidedTips": "Bar jedan alat treba da bude izabran."
});