define({
  "defaultAreaUnit": "ברירת מחדל ליחידת שטח",
  "defaultLengthUnit": "ברירת מחדל ליחידת אורך",
  "metric": "מטרי",
  "imperial": "תקן אמריקאי",
  "squareKilometers": "קילומטרים מר&apos;",
  "squareMeters": "מטרים מר&apos;",
  "squareMiles": "מיילים מר&apos;",
  "squareInches": "אינטשים רבועים",
  "squareFeet": "רגליים מר&apos;",
  "squareYards": "יארדים מר&apos;",
  "squareUSFeet": "רגל מרובע (ארה\"ב)",
  "acres": "אקרים",
  "ares": "עשיריות דונם",
  "hectares": "הקטרים",
  "inches": "אינצ׳ים",
  "feet": "רגליים",
  "yards": "יארדים",
  "miles": "מייל",
  "nauticalMiles": "מיילים ימיים",
  "feetUS": "רגל (ארה\"ב)",
  "meters": "מטרים",
  "kilometers": "קילומטרים",
  "showArea": "שטח",
  "showDistance": "מרחק",
  "showLocation": "מיקום",
  "showtools": "הצג כלי מדידה:",
  "allHidedTips": "יש לבחור לפחות כלי אחד."
});